apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cnj-hello-backend-nodejs-hpa
  namespace: cxp-team-cloudbirds
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cnj-hello-backend-nodejs-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1